import express from "express";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = process.env.PORT || 8080;
const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, "data");
const DATEI = path.join(DATA_DIR, "state.json");
fs.mkdirSync(DATA_DIR, { recursive: true });
const lesen = () => { try { return JSON.parse(fs.readFileSync(DATEI, "utf8")); } catch { return {}; } };
const schreiben = (obj) => { const tmp = DATEI + ".tmp"; fs.writeFileSync(tmp, JSON.stringify(obj)); fs.renameSync(tmp, DATEI); };
const app = express();
app.use(express.json({ limit: "50mb" }));
app.get("/api/state", (_req, res) => res.json({ keys: Object.keys(lesen()) }));
app.get("/api/state/:key", (req, res) => { const a = lesen(); if (!(req.params.key in a)) return res.status(404).json({ error: "not found" }); res.json({ key: req.params.key, value: a[req.params.key] }); });
app.put("/api/state/:key", (req, res) => { if (typeof req.body?.value !== "string") return res.status(400).json({ error: "value (string) fehlt" }); const a = lesen(); a[req.params.key] = req.body.value; schreiben(a); res.json({ key: req.params.key, ok: true }); });
app.delete("/api/state/:key", (req, res) => { const a = lesen(); delete a[req.params.key]; schreiben(a); res.json({ key: req.params.key, deleted: true }); });
app.use(express.static(path.join(__dirname, "dist")));
app.use((_req, res) => res.sendFile(path.join(__dirname, "dist", "index.html")));
app.listen(PORT, () => console.log(`Kanalgang läuft auf Port ${PORT}, Daten in ${DATEI}`));
